services:
  main:
    image: futebot
    container_name: futebot-python
    
    build: .
    volumes:
      - ./data:/app/data  # Mapeia o banco de dados para persistência
    working_dir: /app 
    env_file:
      - .env 
    