services:
  main:
    image: discord.bot:latest
    container_name: futebot
    build: .
    volumes:
      - ./data:/app/data
    working_dir: /app
    env_file:
      - .env
    command: python src/__main__.py
